#!/usr/bin/env bash
# displays Best School 10 times.
# display Best School followed by hi on the 9th iteration

COUNT=0
while [ $COUNT -lt 11 ]
do
	if [ $COUNT -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	COUNT=$(( COUNT + 1 ))
done
